name: Publish NPM package
permissions:
  contents: write
on:
  workflow_run:
    workflows: ["Run Tests"]
    tags:
      - '*'
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    # Require tests to pass before publish
    # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build NPM package
        run: bun run build:npm
      - name: Publish NPM package
        run: |
          cd publish/npm
          bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
