name: Publish NPM package
permissions:
  contents: write
on:
  push:
    tags:
      - '*'
jobs:
  tests:
    uses: ./.github/workflows/tests.yml # Run tests
  publish:
    runs-on: ubuntu-latest
    needs: [tests] # Require tests to pass before publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build NPM package
        run: bun run build:npm
      - name: Publish NPM package
        run: |
          cd publish/npm
          bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
