name: Publish NPM package
permissions:
  # Note: Because this workflow is call from release, the
  # trusted publisher workflow will be release.yml
  # see https://docs.npmjs.com/trusted-publishers
  id-token: write
  contents: write
on:
  # Release workflow calls this after shared test step succeeds
  workflow_call: # Can called from other workflows
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NPM
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Build NPM package
        run: npm run build:npm
      - name: Publish NPM package
        run: |
          cd publish/npm
          npm publish --access public
